[package]
name = "libR-sys"
version = "0.1.2"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Low level bindings to the R programming language."
license = "Apache-2.0"
links = "R"

[dependencies]

[build-dependencies]
bindgen = "0.53.2"
pkg-config = "0.3.17"

