[package]
name = "libR-sys"
version = "0.1.7"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Low level bindings to the R programming language."
license = "MIT"
links = "R"
documentation = "https://extendr.github.io/libR-sys/master/libR_sys/index.html"

[dependencies]

[build-dependencies]
bindgen = "0.53.2"
pkg-config = "0.3.17"
regex = "1"
