[package]
name = "libR-sys"
version = "0.1.12"
authors = [
    "andy-thomason <andy@andythomason.com>",
    "Claus O. Wilke <wilke@austin.utexas.edu>"
]
edition = "2018"
description = "Low level bindings to the R programming language."
license = "MIT"
links = "R"
documentation = "https://docs.rs/libR-sys/latest/libR_sys/"

[dependencies]

[build-dependencies]
bindgen = { version = "0.53.2", optional = true }
regex = { version = "1", optional = true }

[features]
# By default, we generate bindings using bindgen. Turn off default features
# to use pre-computed bindings.
use-bindgen = ["bindgen", "regex"]


[target.'cfg(windows)'.build-dependencies]
winapi = "0.3"
kernel32-sys = "0.2.2"
