name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test_linux:
    name: Run tests (Linux)
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        rust-version: [stable, beta]
        allow-failure: [false]
        include:
          - rust-version: nightly
            allow-failure: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Build
        run: cargo build -vv
        env:
          LIBRSYS_BINDINGS_OUTPUT_PATH: generated_bindings
      - name: Run tests
        run: cargo test -- --nocapture --test-threads=1
      - name: Upload generated bindings
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: Linux ${{ matrix.rust-version }} generated bindings
          path: generated_bindings


  test_macos:
    name: Run tests (macOS)
    runs-on: macos-latest
    strategy:
      matrix:
        rust-version: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install dependencies
        run: brew install llvm r
      - name: Set dynamic environment variables
        run: echo "LIBCLANG_PATH=$(brew --prefix llvm)/lib" >> $GITHUB_ENV
      - name: Build
        run: cargo build -vv
        env:
          LIBRSYS_BINDINGS_OUTPUT_PATH: generated_bindings
      - name: Run tests
        run: cargo test -- --nocapture --test-threads=1
      - name: Run tests on precomputed bindings
        run: cargo test --no-default-features -- --nocapture --test-threads=1
      - name: Upload generated bindings
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: macOS generated bindings
          path: generated_bindings

  test_windows:
    name: Run tests (Windows x86_64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        rust-version: [stable-x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          release: false
          update: false
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          default: true
          components: rustfmt, clippy
      - name: Build
        run: |
          cargo build -vv
        env:
          LIBCLANG_PATH: C:/msys64/mingw64/bin
          LIBRSYS_BINDINGS_OUTPUT_PATH: generated_bindings
      - name: Run tests
        run: cargo test -- --nocapture --test-threads=1
      - name: Run tests on precomputed bindings
        run: cargo test --no-default-features -- --nocapture --test-threads=1
      - name: Upload generated bindings
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: Windows generated bindings
          path: generated_bindings

  test_windows_32bit:
    name: Run tests (Windows i686)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        rust-version: [stable-i686-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          path-type: inherit
          release: false
          update: false
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          default: true
          components: rustfmt, clippy
      - name: Build with precomputed bindings
        run: cargo build -vv --no-default-features
      - name: Run tests on precomputed bindings
        run: cargo test -vv --no-default-features -- --nocapture --test-threads=1

